# Generated by Django 3.1.3 on 2020-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squares_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_users_friends_+', to='squares_app.Users'),
        ),
    ]
