# Generated by Django 3.1.3 on 2020-11-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squares_app', '0002_auto_20201128_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='squares_app.users')),
            ],
        ),
    ]
