# Generated by Django 3.1.3 on 2020-12-02 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squares_app', '0004_auto_20201129_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullplayers',
            name='date_time_appear',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
