# Generated by Django 3.1.3 on 2020-12-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squares_app', '0006_auto_20201202_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullplayers',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='squares_app.users'),
        ),
    ]
