# Generated by Django 3.1.3 on 2020-12-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squares_app', '0008_auto_20201202_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_time_to',
            field=models.DateTimeField(blank=True),
        ),
    ]
