# Generated by Django 3.1.3 on 2020-12-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squares_app', '0009_auto_20201202_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='friends',
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Да', 'Готов играть'), ('Нет', 'Не готов играть')], default='Нет', max_length=3)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend', to='squares_app.users')),
                ('user_friend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_friend', to='squares_app.users')),
            ],
        ),
    ]
