# Generated by Django 3.1.4 on 2021-01-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squares_app', '0014_auto_20201202_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
