# Generated by Django 3.1.3 on 2020-12-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squares_app', '0005_pullplayers_date_time_appear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullplayers',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='squares_app.users', unique=True),
        ),
    ]
